  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: weathervane-test-claim
    annotations:
        volume.beta.kubernetes.io/storage-class: local-storage
  spec:
    accessModes:
     - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
